/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game1;

import Casino.CasinoFirstPage;
import DB.DBBank;
import Timer_Test.Timer2;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author s1601396
 */
public final class Game1 extends javax.swing.JFrame {

    double panos = 1;
    int taso = 1;
    int Lines;
    double lopullinenPanos;
    double lopullinenPanos2;
    double voitto;
    double Kassa;
    static double kassa;
    static double loppukassa;
    double loppuKassa;
    private javax.swing.Timer ajastin;
    private javax.swing.Timer ajastin2;
    private javax.swing.Timer ajastin3;
    private javax.swing.Timer ajastin4;
    private javax.swing.Timer ajastin5;
    private int laskuri = 0;
    private int laskuri2 = 0;
    private int laskuri3 = 0;
    private int laskuri4 = 0;
    private int laskuri5 = 0;
    private int number1 = 0;
    private int number2 = 0;
    private int number3 = 0;
    private int num1;
    private int num2;
    private int num3;
    private int num4;
    private int num5;
    private int num6;
    private int num7;
    private int num8;
    private int num9;

    int Auto = 1;
    int auto = 5;

    /**
     * Creates new form Game1
     */
    public Game1() {
        initComponents();

        DBBank.GameBank();
        jLabel8.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jTextField3.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jToggleButton1.setVisible(false);
        jLabel26.setVisible(false);
        Kassa = kassa;

        loppukassa = loppuKassa;
        toKassa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PlayButton = new javax.swing.JButton();
        KassaLabel = new javax.swing.JLabel();
        KassaField = new javax.swing.JTextField();
        VoittoLabel = new javax.swing.JLabel();
        VoittoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Num9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Num7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Num8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Num6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Num4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Num5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Num1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Num2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Num3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrameLine.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game1");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Panos-1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusCycleRoot(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 43, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/PanosBar.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 43, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 1));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0.10 €");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 44, 54, 25));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Panos+1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 43, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Panos-1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusCycleRoot(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 43, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/PanosBar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 43, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(1, 2, 4));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("1");
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 43, 54, 25));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Panos+1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 43, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Taso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Voitto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Pelaa.png"))); // NOI18N
        PlayButton.setBorder(null);
        PlayButton.setBorderPainted(false);
        PlayButton.setContentAreaFilled(false);
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 40, -1, -1));

        KassaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1KassaJaVoittoFrame.png"))); // NOI18N
        jPanel1.add(KassaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        KassaField.setEditable(false);
        KassaField.setBackground(new java.awt.Color(0, 0, 2));
        KassaField.setForeground(new java.awt.Color(255, 255, 255));
        KassaField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        KassaField.setText("1");
        KassaField.setBorder(null);
        KassaField.setPreferredSize(new java.awt.Dimension(6, 13));
        KassaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KassaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(KassaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 69, 28));

        VoittoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1KassaJaVoittoFrame.png"))); // NOI18N
        jPanel1.add(VoittoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        VoittoField.setEditable(false);
        VoittoField.setBackground(new java.awt.Color(0, 0, 2));
        VoittoField.setForeground(new java.awt.Color(255, 255, 255));
        VoittoField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        VoittoField.setText("0");
        VoittoField.setBorder(null);
        jPanel1.add(VoittoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 80, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kassa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setRequestFocusEnabled(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 73, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1FinalBetFrame.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 55, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 1));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0.10 €");
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 56, 60, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LopullinenPanos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 59, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Panos");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 23, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("€");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 49, 10, 10));

        jButton6.setText("Auto");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 25, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("5");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jButton7.setText("<");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 10, 20));

        jButton8.setText(">");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 10, 20));

        jToggleButton1.setText("Start");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 800, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/PanosFrame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Palaa.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 5));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("JACKPOT");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line1,2,3.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 277, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line1,2,3.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 156, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line1,2,3.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 40, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line2Button.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 282, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line3Button.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line1Button.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 166, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line5Button.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 50, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line4Button.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 282, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line5.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 1, 370, 350));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1Line4.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 53, -1, -1));

        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(125, 100));

        Num9.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num9.setForeground(new java.awt.Color(255, 255, 255));
        Num9.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, 100));

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(125, 100));

        Num7.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num7.setForeground(new java.awt.Color(255, 255, 255));
        Num7.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 130, 100));

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(125, 100));

        Num8.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num8.setForeground(new java.awt.Color(255, 255, 255));
        Num8.setText("0");
        Num8.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 125, 130, 100));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(125, 100));

        Num6.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num6.setForeground(new java.awt.Color(255, 255, 255));
        Num6.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 130, 100));

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(125, 100));

        Num4.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num4.setForeground(new java.awt.Color(255, 255, 255));
        Num4.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 130, 100));

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(125, 100));

        Num5.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num5.setForeground(new java.awt.Color(255, 255, 255));
        Num5.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Num5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 125, 130, 100));

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(125, 100));

        Num1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num1.setForeground(new java.awt.Color(255, 255, 255));
        Num1.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 100));

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(125, 100));

        Num2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num2.setForeground(new java.awt.Color(255, 255, 255));
        Num2.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, 130, 100));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(125, 100));

        Num3.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Num3.setForeground(new java.awt.Color(255, 255, 255));
        Num3.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Num3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrame2.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrame2.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1NumberFrame2.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 580, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Game1_Wall.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        panos = panos + 1;
        if (panos == 10) {
            panos = 9;
        }
        lopullinenPanos = Panos.panos(panos);
        jTextField1.setText(Double.toString(lopullinenPanos) + "0 €");

        lopullinenPanos2 = lopullinenPanos * taso;

        jTextField4.setText(Double.toString(lopullinenPanos2) + "0 €");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panos = panos - 1;
        if (panos == 0) {
            panos = 1;
        }
        lopullinenPanos = Panos.panos(panos);
        jTextField1.setText(Double.toString(lopullinenPanos) + "0 €");

        lopullinenPanos2 = lopullinenPanos * taso;

        jTextField4.setText(Double.toString(lopullinenPanos2) + "0 €");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        taso = taso - 1;
        if (taso <= 0) {
            taso = 1;
        }

        Lines = taso;
        jTextField2.setText(Integer.toString(taso));

        if (Lines == 1) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(false);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel24.setVisible(false);
        } else if (Lines == 2) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel24.setVisible(false);
        } else if (Lines == 3) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
            jLabel20.setVisible(false);
            jLabel24.setVisible(false);
        } else if (Lines == 4) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
            jLabel20.setVisible(false);
            jLabel24.setVisible(true);
        } else if (Lines == 5) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
            jLabel20.setVisible(true);
            jLabel24.setVisible(true);
        }

        if (Lines == 0) {
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel24.setVisible(false);
        }

        lopullinenPanos = Panos.panos(panos);
        lopullinenPanos2 = lopullinenPanos * taso;

        jTextField4.setText(Double.toString(lopullinenPanos2) + "0 €");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        taso = taso + 1;
        if (taso == 6) {
            taso = 5;
        }

        Lines = taso;

        jTextField2.setText(Integer.toString(taso));

        if (Lines == 1) {
            jLabel7.setVisible(true);
        } else if (Lines == 2) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
        } else if (Lines == 3) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
        } else if (Lines == 4) {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
            jLabel24.setVisible(true);
        } else if (Lines == 5) {
            jLabel24.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel19.setVisible(true);
            jLabel20.setVisible(true);
        }
        if (Lines == 0) {
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel24.setVisible(false);
        }

        lopullinenPanos = Panos.panos(panos);
        lopullinenPanos2 = lopullinenPanos * taso;

        jTextField4.setText(Double.toString(lopullinenPanos2) + "0 €");
    }//GEN-LAST:event_jButton4ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //TODO add your handling code here:
        DBBank.getGameBank(Double.parseDouble(KassaField.getText()));
        new CasinoFirstPage().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:

        kassa = Double.parseDouble(KassaField.getText());
        VoittoField.setText("0");
        jTextField3.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);

        laskuri = 0;
        laskuri2 = laskuri;
        laskuri3 = laskuri2;
        number1 = Timer2.num1();
        number1 = Timer2.num1();
        number3 = Timer2.num1();
        if (kassa > 0 && lopullinenPanos2 <= kassa) {
            PlayButton.setEnabled(false);
            num1 = NumeroidenArvonta.num1();
            num2 = NumeroidenArvonta.num2();
            num3 = NumeroidenArvonta.num3();
            num4 = NumeroidenArvonta.num4();
            num5 = NumeroidenArvonta.num5();
            num6 = NumeroidenArvonta.num6();
            num7 = NumeroidenArvonta.num7();
            num8 = NumeroidenArvonta.num8();
            num9 = NumeroidenArvonta.num9();
            ajastinjuttu();
            ajastinjuttu2();
            ajastinjuttu3();

            if (voitto == 0) {
                loppuKassa = kassa - lopullinenPanos2;
                KassaField.setText(Double.toString(loppuKassa));
            } else {
                loppuKassa = (kassa - lopullinenPanos2) + voitto;
                KassaField.setText(Double.toString(loppuKassa));
            }

        } else {
            jTextField3.setVisible(true);
            jTextField3.setText("Ei tarpeeksi rahaa");
        }
        DBBank.getGameBank(loppuKassa);
        try {
            DBBank.updateBank(loppuKassa);
        } catch (SQLException ex) {
            Logger.getLogger(Game1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PlayButtonActionPerformed

    public void Tasot() {
        double taso1Voitto = 0;
        double taso2Voitto = 0;
        double taso3Voitto = 0;
        double taso4Voitto = 0;
        double taso5Voitto = 0;
        double jackPot = 0;

        if (taso == 1) {
            taso1Voitto = VoitonJako.Taso1(num2, num5, num8);

            taso1Voitto = taso1Voitto * lopullinenPanos2;

            if (taso1Voitto > 0) {
                jLabel7.setVisible(true);
            }

            voitto = VoitonJako.voitto(taso1Voitto, taso2Voitto, taso3Voitto, taso4Voitto, taso5Voitto, taso, jackPot);
            VoittoField.setText(Double.toString(voitto));
        } else if (taso == 2) {
            taso1Voitto = VoitonJako.Taso1(num2, num5, num8);
            taso2Voitto = VoitonJako.Taso2(num3, num6, num9);

            if (taso1Voitto > 0) {
                jLabel7.setVisible(true);
            }
            if (taso2Voitto > 0) {
                jLabel8.setVisible(true);
            }

            taso1Voitto = taso1Voitto * lopullinenPanos2;
            taso2Voitto = taso2Voitto * lopullinenPanos2;

            voitto = VoitonJako.voitto(taso1Voitto, taso2Voitto, taso3Voitto, taso4Voitto, taso5Voitto, taso, jackPot);
            VoittoField.setText(Double.toString(voitto));
        } else if (taso == 3) {
            taso1Voitto = VoitonJako.Taso1(num2, num5, num8);
            taso2Voitto = VoitonJako.Taso2(num3, num6, num9);
            taso3Voitto = VoitonJako.Taso3(num1, num4, num7);

            if (taso1Voitto > 0) {
                jLabel7.setVisible(true);
            }
            if (taso2Voitto > 0) {
                jLabel8.setVisible(true);
            }
            if (taso3Voitto > 0) {
                jLabel19.setVisible(true);
            }

            taso1Voitto = taso1Voitto * lopullinenPanos2;
            taso2Voitto = taso2Voitto * lopullinenPanos2;
            taso3Voitto = taso3Voitto * lopullinenPanos2;

            voitto = VoitonJako.voitto(taso1Voitto, taso2Voitto, taso3Voitto, taso4Voitto, taso5Voitto, taso, jackPot);
            VoittoField.setText(Double.toString(voitto));
        } else if (taso == 4) {

            taso1Voitto = VoitonJako.Taso1(num2, num5, num8);
            taso2Voitto = VoitonJako.Taso2(num3, num6, num9);
            taso3Voitto = VoitonJako.Taso3(num1, num4, num7);
            taso4Voitto = VoitonJako.Taso4(num1, num5, num9);

            if (taso1Voitto > 0) {
                jLabel7.setVisible(true);
            }
            if (taso2Voitto > 0) {
                jLabel8.setVisible(true);
            }
            if (taso3Voitto > 0) {
                jLabel19.setVisible(true);
            }
            if (taso4Voitto > 0) {
                jLabel24.setVisible(true);
            }

            taso1Voitto = taso1Voitto * lopullinenPanos2;
            taso2Voitto = taso2Voitto * lopullinenPanos2;
            taso3Voitto = taso3Voitto * lopullinenPanos2;
            taso4Voitto = taso4Voitto * lopullinenPanos2;

            voitto = VoitonJako.voitto(taso1Voitto, taso2Voitto, taso3Voitto, taso4Voitto, taso5Voitto, taso, jackPot);
            VoittoField.setText(Double.toString(voitto));
        } else if (taso == 5) {

            taso1Voitto = VoitonJako.Taso1(num2, num5, num8);
            taso2Voitto = VoitonJako.Taso2(num3, num6, num9);
            taso3Voitto = VoitonJako.Taso3(num1, num4, num7);
            taso4Voitto = VoitonJako.Taso4(num1, num5, num9);
            taso5Voitto = VoitonJako.Taso5(num3, num5, num7);
            jackPot = VoitonJako.JackPot(num1, num2, num3, num4, num5, num6, num7, num8, num9);

            if (taso1Voitto > 0) {
                jLabel7.setVisible(true);
            }
            if (taso2Voitto > 0) {
                jLabel8.setVisible(true);
            }
            if (taso3Voitto > 0) {
                jLabel19.setVisible(true);
            }
            if (taso4Voitto > 0) {
                jLabel24.setVisible(true);
            }
            if (taso5Voitto > 0) {
                jLabel20.setVisible(true);
            }
            if (jackPot == 50) {
                jLabel25.setVisible(true);
                jackPot = jackPot * lopullinenPanos2;
            } else {
                taso1Voitto = taso1Voitto * lopullinenPanos2;
                taso2Voitto = taso2Voitto * lopullinenPanos2;
                taso3Voitto = taso3Voitto * lopullinenPanos2;
                taso4Voitto = taso4Voitto * lopullinenPanos2;
                taso5Voitto = taso5Voitto * lopullinenPanos2;
            }

            voitto = VoitonJako.voitto(taso1Voitto, taso2Voitto, taso3Voitto, taso4Voitto, taso5Voitto, taso, jackPot);
            VoittoField.setText(Double.toString(voitto));

        }
    }

    public void ajastinjuttu() {
        ajastin = new javax.swing.Timer(70, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero();

                if (number1 == 10) {
                    number1 = 1;
                }
                Num1.setText(Integer.toString(number1));
                number1++;
                if (number1 == 10) {
                    number1 = 1;
                }
                Num2.setText(Integer.toString(number1));
                number1++;
                if (number1 == 10) {
                    number1 = 1;
                }
                Num3.setText(Integer.toString(number1));
                number1++;
                if (laskuri == 30) {
                    ajastin.stop();
                    Num1.setText(Integer.toString(num1));
                    Num2.setText(Integer.toString(num2));
                    Num3.setText(Integer.toString(num3));
                    System.out.println(num1);
                    System.out.println(num2);
                    System.out.println(num3);
                }
            }
        });
        ajastin.setInitialDelay(100);

        ajastin.start();
    }

    public void ajastinjuttu2() {
        ajastin2 = new javax.swing.Timer(70, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero2();

                if (number2 == 10) {
                    number2 = 1;
                }
                Num4.setText(Integer.toString(number2));
                number2++;
                if (number2 == 10) {
                    number2 = 1;
                }
                Num5.setText(Integer.toString(number2));
                number2++;
                if (number2 == 10) {
                    number2 = 1;
                }
                Num6.setText(Integer.toString(number2));
                number2++;
                if (laskuri2 == 40) {
                    ajastin2.stop();
                    Num4.setText(Integer.toString(num4));
                    Num5.setText(Integer.toString(num5));
                    Num6.setText(Integer.toString(num6));
                    System.out.println(num4);
                    System.out.println(num5);
                    System.out.println(num6);

                }

            }
        });
        ajastin2.setInitialDelay(0);

        ajastin2.start();
    }

    public void ajastinjuttu3() {
        ajastin3 = new javax.swing.Timer(70, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero3();

                if (number3 == 10) {
                    number3 = 1;
                }
                Num7.setText(Integer.toString(number3));
                number3++;
                if (number3 == 10) {
                    number3 = 1;
                }
                Num8.setText(Integer.toString(number3));
                number3++;
                if (number3 == 10) {
                    number3 = 1;
                }
                Num9.setText(Integer.toString(number3));
                number3++;
                if (laskuri3 == 50) {
                    ajastin3.stop();
                    Num7.setText(Integer.toString(num7));
                    Num8.setText(Integer.toString(num8));
                    Num9.setText(Integer.toString(num9));
                    System.out.println(num7);
                    System.out.println(num8);
                    System.out.println(num9);
                    Tasot();
                    PlayButton.setEnabled(true);
                }
            }
        });
        ajastin3.setInitialDelay(0);
        ajastin3.start();

    }

    public void ajastinjuttu5() {
        ajastin5 = new javax.swing.Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero5();
                ajastinjuttu4();

                if (laskuri5 == auto) {
                    ajastin5.stop();

                }
            }
        });
        ajastin5.setInitialDelay(1000);
        ajastin5.start();

    }

    private void paivitanumero() {
        laskuri++;

    }

    private void paivitanumero2() {
        laskuri2++;

    }

    private void paivitanumero3() {
        laskuri3++;

    }

    public void ajastinjuttu4() {
        laskuri = 0;
        laskuri2 = laskuri;
        laskuri3 = laskuri2;
        System.out.println("Ajastin go");
        kassa = Double.parseDouble(KassaField.getText());
        VoittoField.setText("0");
        jTextField3.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);

        number1 = Timer2.num1();
        number1 = Timer2.num1();
        number3 = Timer2.num1();
        if (kassa > 0 && lopullinenPanos2 <= kassa) {
            PlayButton.setEnabled(false);
            num1 = NumeroidenArvonta.num1();
            num2 = NumeroidenArvonta.num2();
            num3 = NumeroidenArvonta.num3();
            num4 = NumeroidenArvonta.num4();
            num5 = NumeroidenArvonta.num5();
            num6 = NumeroidenArvonta.num6();
            num7 = NumeroidenArvonta.num7();
            num8 = NumeroidenArvonta.num8();
            num9 = NumeroidenArvonta.num9();
            ajastinjuttu();
            ajastinjuttu2();
            ajastinjuttu3();

            if (voitto == 0) {
                loppuKassa = kassa - lopullinenPanos2;
                KassaField.setText(Double.toString(loppuKassa));
            } else {
                loppuKassa = (kassa - lopullinenPanos2) + voitto;
                KassaField.setText(Double.toString(loppuKassa));
            }

        } else {

            jTextField3.setVisible(true);
            jTextField3.setText("Ei tarpeeksi rahaa");

        }
        DBBank.getGameBank(loppuKassa);
        try {
            DBBank.updateBank(loppuKassa);
        } catch (SQLException ex) {
            Logger.getLogger(Game1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void paivitanumero5() {
        laskuri5++;

    }

    public static void kassa(double Kassa2) {
        kassa = Kassa2;
    }

    public void toKassa() {
        KassaField.setText(Double.toString(Kassa));
    }


    private void KassaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KassaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KassaFieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Auto = Auto - 1;
        if (Auto <= 0) {
            Auto = 1;
        }
        auto = AutoGame.Auto(Auto);
        System.out.println(auto + " = auto");
        jLabel26.setText(Integer.toString(auto));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Auto = Auto + 1;
        if (Auto == 6) {
            Auto = 5;
        }

        auto = AutoGame.Auto(Auto);
        System.out.println(auto + " = auto");
        jLabel26.setText(Integer.toString(auto));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jToggleButton1.setVisible(true);
        jLabel26.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            ajastinjuttu5();
            jToggleButton1.setText("Stop");
        } else {
            jToggleButton1.setText("Start");
            ajastin5.stop();
            laskuri5 = 0;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KassaField;
    private javax.swing.JLabel KassaLabel;
    private javax.swing.JLabel Num1;
    private javax.swing.JLabel Num2;
    private javax.swing.JLabel Num3;
    private javax.swing.JLabel Num4;
    private javax.swing.JLabel Num5;
    private javax.swing.JLabel Num6;
    private javax.swing.JLabel Num7;
    private javax.swing.JLabel Num8;
    private javax.swing.JLabel Num9;
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField VoittoField;
    private javax.swing.JLabel VoittoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
