/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timer_Test;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author osku0
 */
public class timer extends javax.swing.JFrame {

    int moi = 0;
    private javax.swing.Timer ajastin;
    private javax.swing.Timer ajastin2;
    private javax.swing.Timer ajastin3;
    private int laskuri = 0;
    private int laskuri2 = 0;
    private int laskuri3 = 0;
    private int num = 0;
    private int num2 = 0;
    private int num3 = 0;

    /**
     * Creates new form timer
     */
    public timer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Num1 = new javax.swing.JLabel();
        Num2 = new javax.swing.JLabel();
        Num3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Num1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num1.setText("0");
        jPanel1.add(Num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 50, 50));

        Num2.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num2.setText("0");
        jPanel1.add(Num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 50, 50));

        Num3.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num3.setText("0");
        jPanel1.add(Num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 220));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 30, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        laskuri = 0;
        laskuri2 = laskuri;
        laskuri3 = laskuri2;
        ajastin = new javax.swing.Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero();

                num = Timer2.num1();
                Num1.setText(Integer.toString(num));
               
            }
        });
        ajastin.setInitialDelay(0);

        ajastin.start();
        
        
        ajastin2 = new javax.swing.Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero2();
                if (laskuri2 >= 29) {
                    num = Timer2.num1();
                }

                Num2.setText(Integer.toString(num));

            }
        });
        ajastin2.setInitialDelay(200);

        ajastin2.start();

        ajastin3 = new javax.swing.Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero3();
                if (laskuri3 >= 38) {
                    num = Timer2.num1();
                }

                Num3.setText(Integer.toString(num));

            }
        });
        ajastin3.setInitialDelay(500);
        ajastin3.start();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void paivitanumero() {
        laskuri++;
        System.out.println(laskuri);
        if (laskuri == 30) {
            ajastin.stop();
        }
    }

    private void paivitanumero2() {
        laskuri2++;
        System.out.println(laskuri2);
        if (laskuri2 == 40) {
            ajastin2.stop();
        }
    }

    private void paivitanumero3() {
        laskuri3++;
        System.out.println(laskuri3);
        if (laskuri3 == 50) {
            ajastin3.stop();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Num1;
    private javax.swing.JLabel Num2;
    private javax.swing.JLabel Num3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
