/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timer_Test;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author osku0
 */
public class timer extends javax.swing.JFrame {

    private javax.swing.Timer ajastin;
    private javax.swing.Timer ajastin2;
    private javax.swing.Timer ajastin3;
    private int laskuri = 0;
    private int laskuri2 = 0;
    private int laskuri3 = 0;

    private int num = 0;
    private int num2 = 0;
    private int num3 = 0;

    private int luku = 9;
    private int luku2 = 8;
    private int luku3 = 7;
    private int luku4 = 4;
    private int luku5 = 5;
    private int luku6 = 4;
    private int luku7 = 3;
    private int luku8 = 2;
    private int luku9 = 1;

    /**
     * Creates new form timer
     */
    public timer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Num1 = new javax.swing.JLabel();
        Num2 = new javax.swing.JLabel();
        Num3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Num4 = new javax.swing.JLabel();
        Num5 = new javax.swing.JLabel();
        Num6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Num7 = new javax.swing.JLabel();
        Num8 = new javax.swing.JLabel();
        Num9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Num1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num1.setText("0");
        jPanel1.add(Num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 50, 50));

        Num2.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num2.setText("0");
        jPanel1.add(Num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 50, 50));

        Num3.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num3.setText("0");
        jPanel1.add(Num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 220));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 30, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Num4.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num4.setText("0");
        jPanel2.add(Num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 50, 50));

        Num5.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num5.setText("0");
        jPanel2.add(Num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 50, 50));

        Num6.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num6.setText("0");
        jPanel2.add(Num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 220));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Num7.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num7.setText("0");
        jPanel3.add(Num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 50, 50));

        Num8.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num8.setText("0");
        jPanel3.add(Num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 50, 50));

        Num9.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Num9.setText("0");
        jPanel3.add(Num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 50, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        laskuri = 0;
        laskuri2 = laskuri;
        laskuri3 = laskuri2;

        ajastin = new javax.swing.Timer(85, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero();

                if (luku == 10) {
                    luku = 1;
                }
                Num1.setText(Integer.toString(luku));
                luku++;
                if (luku2 == 10) {
                    luku2 = 1;
                }
                Num2.setText(Integer.toString(luku2));
                luku2++;
                if (luku3 == 10) {
                    luku3 = 1;
                }
                Num3.setText(Integer.toString(luku3));
                luku3++;

            }
        });
        ajastin.setInitialDelay(0);

        ajastin.start();

        ajastin2 = new javax.swing.Timer(85, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero2();

                if (luku4 == 10) {
                    luku4 = 1;
                }
                Num4.setText(Integer.toString(luku4));
                luku4++;
                if (luku5 == 10) {
                    luku5 = 1;
                }
                Num5.setText(Integer.toString(luku5));
                luku5++;
                if (luku6 == 10) {
                    luku6 = 1;
                }
                Num6.setText(Integer.toString(luku6));
                luku6++;

            }
        });
        ajastin2.setInitialDelay(0);

        ajastin2.start();

        ajastin3 = new javax.swing.Timer(85, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                paivitanumero3();

                if (luku7 == 10) {
                    luku7 = 1;
                }
                Num7.setText(Integer.toString(luku7));
                luku7++;
                if (luku8 == 10) {
                    luku8 = 1;
                }
                Num8.setText(Integer.toString(luku8));
                luku8++;
                if (luku9 == 10) {
                    luku9 = 1;
                }
                Num9.setText(Integer.toString(luku9));
                luku9++;

            }
        });
        ajastin3.setInitialDelay(0);
        ajastin3.start();

        num = Timer2.num1();
        num2 = Timer2.num1();
        num3 = Timer2.num1();
        Num1.setText(Integer.toString(num));
        Num2.setText(Integer.toString(num));
        Num3.setText(Integer.toString(num));
        Num4.setText(Integer.toString(num2));
        Num5.setText(Integer.toString(num2));
        Num6.setText(Integer.toString(num2));
        Num7.setText(Integer.toString(num3));
        Num8.setText(Integer.toString(num3));
        Num9.setText(Integer.toString(num3));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void paivitanumero() {
        laskuri++;
        System.out.println(laskuri);
        if (laskuri == 30) {
            ajastin.stop();
        }
    }

    private void paivitanumero2() {
        laskuri2++;
        System.out.println(laskuri2);
        if (laskuri2 == 40) {
            ajastin2.stop();
        }
    }

    private void paivitanumero3() {
        laskuri3++;
        System.out.println(laskuri3);
        if (laskuri3 == 50) {
            ajastin3.stop();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Num1;
    private javax.swing.JLabel Num2;
    private javax.swing.JLabel Num3;
    public javax.swing.JLabel Num4;
    private javax.swing.JLabel Num5;
    private javax.swing.JLabel Num6;
    public javax.swing.JLabel Num7;
    private javax.swing.JLabel Num8;
    private javax.swing.JLabel Num9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
